//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_TURBO.AZ__NovruzHoliday_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> EPowID { get; set; }
        public Nullable<int> FuelID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Car_Year Car_Year { get; set; }
        public virtual EnginerPower EnginerPower { get; set; }
        public virtual Fuel Fuel { get; set; }
        public virtual Model Model { get; set; }
        public virtual Status Status { get; set; }
    }
}
